'use client';
import {useState} from 'react';
import {useSite} from './context';
import {uid,colors,fabrics,styles} from '@/lib/rasavatt/data';
import {imageFiles,styleImages} from '@/lib/rasavatt/visuals';
import {Button,Heading,Photo,Link,Tabs,Empty} from './ui';
const looks:Record<number,{title:string;description:string;tags:string[]}>= {
 4:{title:'A bridal story in rose.',description:'A flowing rose lehenga, intricate gold embroidery and a silhouette made for a memorable celebration.',tags:['Bridal','Rose','Embroidery','Silk']},
 2:{title:'The quiet elegance of sage.',description:'Soft sage silk, a golden border and an effortless drape for intimate celebrations.',tags:['Saree','Sage','Silk','Elegant']},
 6:{title:'A celebration in emerald.',description:'Rich emerald fabric and gold handwork bring a festive silhouette to life.',tags:['Festive','Emerald','Gold','Lehenga']},
 5:{title:'An evening in lavender.',description:'A gentle lavender palette and graceful drape for an evening occasion.',tags:['Lavender','Saree','Evening','Elegant']},
 8:{title:'After-dark, reimagined.',description:'A midnight gown with golden detailing, inspired by contemporary Indian eveningwear.',tags:['Midnight','Gown','Indo-Western','Party']},
 7:{title:'Ivory, with a little gold.',description:'A refined festive kurta set that balances comfortable tailoring with thoughtful detail.',tags:['Ivory','Kurta','Festive','Minimal']},
 14:{title:'Easy days in terracotta.',description:'Relaxed linen, natural light and an uncomplicated silhouette for everyday moments.',tags:['Terracotta','Linen','Casual','Relaxed']},
};
export function Inspiration(){const {path,state,setState,go,toast}=useSite();const [tab,setTab]=useState('Outfits'),[savedOnly,setSavedOnly]=useState(false);const id=Number(path.split('/')[3]);const look=looks[id];const saveKey='inspiration-'+id;const saved=state.wishlist.includes(saveKey);
const useLook=(n:number)=>{setState(s=>({...s,brief:{...s.brief,reference:String(n)}}));go('/create/inspiration')};
if(id&&look)return <section className="section"><div className="inspiration-detail"><Photo image={id} alt={look.title}/><div><p className="eyebrow">THE INSPIRATION EDIT</p><h1>{look.title}</h1><p>{look.description}</p><div className="static-tags">{look.tags.map(t=><span key={t}>{t}</span>)}</div><div className="actions"><Button onClick={()=>setState(s=>({...s,wishlist:saved?s.wishlist.filter(x=>x!==saveKey):[...s.wishlist,saveKey]}))}>{saved?'Unsave inspiration':'Save inspiration'}</Button><Button secondary onClick={()=>{const item={id:uid(),type:'image',text:look.title,image:'/images/'+imageFiles[id],x:15,y:15};setState(s=>({...s,boards:s.boards.length?s.boards.map((b,i)=>i===0?{...b,items:[...b.items,item]}:b):[{id:uid(),name:'My inspiration',items:[item]}]}));toast('Added to your first moodboard')}}>Add to moodboard</Button><Button secondary onClick={()=>useLook(id)}>Create a look like this</Button></div><Link className="text-link" to={'/search/results?q='+encodeURIComponent(look.tags[0])}>Find similar designers and outfits</Link><div className="panel"><h3>Make it your own.</h3><p>Use this look as a starting point. Your designer will help refine the silhouette, fabric and fit.</p><Link to="/discover">Find your creative partner</Link></div></div></div><Heading title="More to inspire you."/><div className="three-grid">{Object.keys(looks).map(Number).filter(n=>n!==id).slice(0,3).map(n=><Link key={n} to={'/profile/inspiration/'+n}><Photo image={n}/><h3>{looks[n].title}</h3></Link>)}</div></section>;
return <section className="section"><Heading eyebrow="SAVE THE DETAILS YOU LOVE" title="Your inspiration edit."/><div className="row between"><Tabs items={['Outfits','Fabrics','Colors','Styles']} value={tab} onChange={setTab}/><label className="check"><input type="checkbox" checked={savedOnly} onChange={e=>setSavedOnly(e.target.checked)}/>Saved only</label></div>{tab==='Colors'?<div className="color-grid">{Object.entries(colors).map(([name,hex])=><button key={name} onClick={()=>{setState(s=>({...s,brief:{...s.brief,colors:[name]}}));go('/create/colors')}}><span style={{background:hex}}/>{name}</button>)}</div>:tab==='Fabrics'?<div className="three-grid">{fabrics.map(f=><button className="panel fabric-inspiration" key={f} onClick={()=>{setState(s=>({...s,brief:{...s.brief,fabric:f}}));go('/create/fabric')}}><div className={'fabric fabric-'+f.toLowerCase()}/><h3>{f}</h3><p>Explore texture, drape and colour with your designer.</p></button>)}</div>:tab==='Styles'?<div className="three-grid">{styles.filter(s=>!savedOnly||state.wishlist.includes('inspiration-'+styleImages[s])).map(s=><Link to={'/profile/inspiration/'+(looks[styleImages[s]]?styleImages[s]:14)} key={s}><Photo image={styleImages[s]} alt={s}/><h3>{s}</h3></Link>)}</div>:<div className="three-grid inspiration-gallery">{Object.keys(looks).map(Number).filter(n=>!savedOnly||state.wishlist.includes('inspiration-'+n)).map(n=><article key={n}><Link to={'/profile/inspiration/'+n}><Photo image={n} alt={looks[n].title}/><h3>{looks[n].title}</h3></Link><button className="text-link" onClick={()=>useLook(n)}>Use this inspiration</button></article>)}</div>}{savedOnly&&!state.wishlist.some(x=>x.startsWith('inspiration-'))&&<Empty title="Your inspiration collection starts here." text="Open a look and save the details you love."/>}</section>
}
