'use client';
import {ReactNode,useState} from 'react';
import {Heart,Star,ArrowUpRight,Flower2,Check,X,UploadCloud} from 'lucide-react';
import {useSite} from './context';
import {Product,Designer,money} from '@/lib/rasavatt/data';
export function Link({to,children,className=''}:{to:string;children:ReactNode;className?:string}){const {go}=useSite();return <a href={to} className={className} onClick={e=>{if(!e.ctrlKey&&!e.metaKey){e.preventDefault();go(to);}}}>{children}</a>}
export function Button({children,to,onClick,secondary=false,disabled=false,type='button'}:{children:ReactNode;to?:string;onClick?:()=>void;secondary?:boolean;disabled?:boolean;type?:'button'|'submit'}){const {go}=useSite();return <button type={type} disabled={disabled} className={'button '+(secondary?'secondary':'')} onClick={onClick||(()=>to&&go(to))}>{children}</button>}
export function Logo(){return <Link to="/home" className="brand"><Flower2 size={36} strokeWidth={1}/><span>RASAVATT</span><small>CUSTOM FASHION, YOUR WAY</small></Link>}
export function Photo({image=4,className='',alt='Indian couture editorial'}:{image?:number;className?:string;alt?:string}){return <div className={'fashion-photo '+className}><img src={'/images/i'+image+'.png'} alt={alt} loading="lazy" onError={e=>{e.currentTarget.src='/images/i4.png'}}/></div>}
export function Heading({eyebrow,title,description,children}:{eyebrow?:string;title:string;description?:string;children?:ReactNode}){return <div className="page-heading"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{description&&<p className="muted">{description}</p>}</div>{children}</div>}
export function Empty({title,text,to,label='Explore collections'}:{title:string;text:string;to?:string;label?:string}){return <div className="empty"><Flower2 size={48} strokeWidth={1}/><h2>{title}</h2><p>{text}</p>{to&&<Button to={to}>{label}</Button>}</div>}
export function Tabs({items,value,onChange}:{items:string[];value:string;onChange:(v:string)=>void}){return <div className="tabs" role="tablist">{items.map(x=><button key={x} role="tab" aria-selected={x===value} className={x===value?'active':''} onClick={()=>onChange(x)}>{x}</button>)}</div>}
export function Chips({items,selected,onChange,multiple=false}:{items:string[];selected:string|string[];onChange:(v:string[])=>void;multiple?:boolean}){const list=Array.isArray(selected)?selected:[selected];return <div className="chips">{items.map(x=><button type="button" aria-pressed={list.includes(x)} key={x} className={list.includes(x)?'selected':''} onClick={()=>onChange(multiple?(list.includes(x)?list.filter(v=>v!==x):[...list,x]):[x])}>{list.includes(x)&&<Check size={15}/>} {x}</button>)}</div>}
export function Field({label,...props}:{label:string}&React.InputHTMLAttributes<HTMLInputElement>){return <label className="field"><span>{label}</span><input {...props}/></label>}
export function ProductCard({product:p}:{product:Product}){const {state,setState}=useSite();const saved=state.wishlist.includes(p.id);return <article className="product-card"><Link to={'/product/'+p.id}><Photo image={p.image} alt={p.name}/></Link><button className={'heart '+(saved?'saved':'')} aria-label={(saved?'Remove from':'Add to')+' wishlist'} onClick={()=>setState(s=>({...s,wishlist:saved?s.wishlist.filter(id=>id!==p.id):[...s.wishlist,p.id]}))}><Heart size={19} fill={saved?'currentColor':'none'}/></button><div className="product-meta"><span>{p.category} · {p.fabric}</span><span><Star size={12} fill="currentColor"/> {p.rating}</span></div><Link to={'/product/'+p.id}><h3>{p.name}</h3></Link><strong>{money(p.price)}</strong></article>}
export function DesignerCard({designer:d}:{designer:Designer}){const {state,setState}=useSite();return <article className="designer-card"><Link to={'/designer/'+d.id}><Photo image={d.image} alt={d.name}/></Link><div className="padded"><div className="row between"><h3>{d.name}</h3><button className="icon-button" aria-label="Save designer" onClick={()=>setState(s=>({...s,wishlist:s.wishlist.includes(d.id)?s.wishlist.filter(x=>x!==d.id):[...s.wishlist,d.id]}))}><Heart size={19} fill={state.wishlist.includes(d.id)?'currentColor':'none'}/></button></div><p className="muted">{d.specialty}</p><div className="row between"><span>★ {d.rating} · {d.location}</span><span>From {money(d.price)}</span></div><Link className="text-link" to={'/designer/'+d.id}>Meet the designer <ArrowUpRight size={16}/></Link></div></article>}
export function Upload({onUpload,label='Add photos or inspiration',accept='image/*'}:{onUpload:(url:string,name:string)=>void;label?:string;accept?:string}){const [error,setError]=useState('');return <div><label className="upload"><UploadCloud/><strong>{label}</strong><span>Choose a file · Up to 3 MB</span><input type="file" accept={accept} onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>3*1024*1024){setError('Please choose a file smaller than 3 MB.');return;}setError('');const r=new FileReader();r.onload=()=>onUpload(String(r.result),f.name);r.readAsDataURL(f);e.target.value='';}}/></label>{error&&<p role="alert" className="error">{error}</p>}</div>}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){return <div className="modal-backdrop" onClick={onClose}><section className="modal" role="dialog" aria-modal="true" aria-label={title} onClick={e=>e.stopPropagation()}><div className="row between"><h2>{title}</h2><button autoFocus className="icon-button" aria-label="Close" onClick={onClose}><X/></button></div>{children}</section></div>}
export function Rating({value,onChange}:{value:number;onChange?:(n:number)=>void}){return <div className="stars">{[1,2,3,4,5].map(n=><button type="button" key={n} disabled={!onChange} aria-label={n+' stars'} onClick={()=>onChange?.(n)}><Star fill={n<=value?'currentColor':'none'}/></button>)}</div>}
