'use client';
import {useState,useEffect,useCallback} from 'react';
import {Search,Heart,ShoppingBag,User,Menu,X,Bell,Home as HomeIcon,Compass,Scissors,Package,Ruler,Image,Star,Settings,HelpCircle,LogOut} from 'lucide-react';
import {State,initialState} from '@/lib/rasavatt/data';
import {customerService} from '@/lib/rasavatt/service';
import {Context} from './context';
import {Logo,Link,Button,Photo} from './ui';
import {Home,Collections,ProductPage,Discover,DesignerPage,Wishlist} from './Storefront';
import {CartCheckout,Payment,Orders} from './Commerce';
import {CreateHub,Brief,BodyScan} from './Create';
import {Chat,Studio} from './Studio';
import {Auth} from './Auth';
import {Account} from './Account';
import {Information} from './Information';
import {MemberHome,WelcomeJourney,StyleJourney,SearchExperience,ReviewsPage,ScreenDirectory} from './Journey';
import {SizeGuide,AccountPreferences} from './Extras';
const memberRoutes=['/profile','/orders','/checkout','/payment','/chat','/studio','/notifications','/settings','/body-scan'];
const needsMember=(p:string)=>memberRoutes.some(r=>p===r||p.startsWith(r+'/'))||p.startsWith('/create/');
const sidebar=[['Explore',HomeIcon,'Home','/home'],['Explore',Compass,'Discover designers','/discover'],['Explore',ShoppingBag,'Ready to wear','/ready-made'],['Create',Scissors,'Create an outfit','/create'],['Create',Image,'Inspiration','/profile/inspiration'],['Create',Ruler,'Measurements','/profile/measurements'],['Your world',Package,'My orders','/orders'],['Your world',Heart,'Wishlist','/wishlist'],['Your world',Star,'My reviews','/profile/reviews'],['Your world',User,'My profile','/profile']] as const;
export default function Website(){
 const [state,setState]=useState<State>(initialState),[path,setPath]=useState('/'),[revision,setRevision]=useState(0),[ready,setReady]=useState(false),[message,setMessage]=useState(''),[menu,setMenu]=useState(false),[online,setOnline]=useState(true);
 const toast=useCallback((m:string)=>setMessage(m),[]);
 const go=useCallback((url:string)=>{if(!url.startsWith('/')||url.startsWith('//'))return;window.history.pushState({},'',url);setPath(url.split('?')[0]);setRevision(v=>v+1);setMenu(false);document.querySelectorAll('.nav-dropdown[open]').forEach(el=>el.removeAttribute('open'));window.scrollTo({top:0,behavior:'instant'});},[]);
 useEffect(()=>{customerService.load().then(s=>{setState(s);setReady(true)}).catch(e=>setMessage(e.message));setPath(window.location.pathname);setOnline(navigator.onLine);const pop=()=>{setPath(window.location.pathname);setRevision(v=>v+1);setMenu(false)};const network=()=>setOnline(navigator.onLine);window.addEventListener('popstate',pop);window.addEventListener('online',network);window.addEventListener('offline',network);return()=>{window.removeEventListener('popstate',pop);window.removeEventListener('online',network);window.removeEventListener('offline',network)}},[]);
 useEffect(()=>{if(!ready)return;const timer=setTimeout(()=>{try{customerService.save(state).catch(e=>setMessage(e.message))}catch{setMessage('Device storage is full. Remove unused photos and retry.')}},500);return()=>clearTimeout(timer)},[state,ready]);
 useEffect(()=>{document.documentElement.dataset.theme=state.dark||path==='/home/dark'?'dark':'light'},[state.dark,path]);
 useEffect(()=>{if(message){const t=setTimeout(()=>setMessage(''),5000);return()=>clearTimeout(t)}},[message]);
 const authPage=['/login','/signup','/otp','/forgot-password'].includes(path),onboarding=path.startsWith('/onboarding')||path.startsWith('/preferences'),welcome=path.startsWith('/welcome')||path==='/splash';
 const gated=needsMember(path)&&!state.user;
 const workspace=!!state.user&&!authPage&&!onboarding&&!welcome&&path!=='/'&&path!=='/our-story'&&path!=='/contact';
 let content;
 if(gated)content=<section className="sign-in-gate"><Photo image={2}/><div><p className="eyebrow">YOUR PERSONAL RASAVATT WORLD</p><h1>A little more personal.<br/><em>A little more you.</em></h1><p>Sign in to save your designs, manage your measurements and follow your outfit’s journey.</p><div className="actions"><Button to={'/login?returnTo='+encodeURIComponent(path)}>Sign in to continue</Button><Button secondary to={'/signup?returnTo='+encodeURIComponent(path)}>Create account</Button></div><Link className="text-link" to="/discover">Keep exploring designers</Link></div></section>;
 else if(path==='/'||path.startsWith('/home'))content=state.user?<MemberHome/>:<Home/>;
 else if(welcome)content=<WelcomeJourney/>;
 else if(onboarding)content=<StyleJourney/>;
 else if(authPage)content=<Auth key={path}/>;
 else if(path==='/screens')content=<ScreenDirectory/>;
 else if(path==='/reviews')content=<ReviewsPage/>;
 else if(path.startsWith('/search'))content=<SearchExperience key={path}/>;
 else if(path==='/collections'||path==='/ready-made')content=<Collections key={path+revision}/>;
 else if(path.startsWith('/product/'))content=<ProductPage key={path}/>;
 else if(path==='/discover')content=<Discover/>;
 else if(path.startsWith('/designer/'))content=<DesignerPage/>;
 else if(path==='/wishlist')content=<Wishlist/>;
 else if(path==='/cart'||path==='/checkout')content=<CartCheckout key={path}/>;
 else if(path.startsWith('/payment'))content=<Payment key={path}/>;
 else if(path.startsWith('/orders'))content=<Orders key={path}/>;
 else if(path==='/create')content=<CreateHub/>;
 else if(path.startsWith('/create/'))content=<Brief key={path}/>;
 else if(path.startsWith('/chat/'))content=<Chat key={path}/>;
 else if(path==='/support')content=<Chat support/>;
 else if(path.startsWith('/studio/'))content=<Studio/>;
 else if(['/profile/privacy','/profile/permissions','/profile/linked-accounts','/profile/security'].includes(path))content=<AccountPreferences key={path}/>;
 else if(path.startsWith('/profile'))content=<Account key={path}/>;
 else if(path==='/size-guide')content=<SizeGuide/>;
 else if(path==='/body-scan')content=<BodyScan/>;
 else content=<Information key={path}/>;
 const cartCount=state.cart.reduce((a,x)=>a+x.quantity,0);
 const signOut=()=>{setState(s=>({...s,user:null}));go('/home');toast('You are signed out')};
 return <Context.Provider value={{state,setState,path,go,toast}}><div className={workspace?'website member-site':'website guest-site'}><a href="#main" className="skip-link">Skip to content</a>{!workspace&&<div className="announcement">Thoughtfully designed. Individually crafted. Uniquely yours.</div>}<header className="site-header"><Logo/>{workspace?<nav aria-label="Member navigation" className={'member-topnav '+(menu?'open':'')}><Link to="/home" className={path==='/home'?'active':''}>Home</Link><Link to="/discover" className={path.startsWith('/discover')?'active':''}>Discover designers</Link><Link to="/ready-made" className={path==='/ready-made'?'active':''}>Ready to wear</Link><details className="nav-dropdown"><summary>Create</summary><div className="nav-dropdown-panel">{sidebar.filter(x=>x[0]==='Create').map(([,Icon,label,url])=><Link key={url} to={url}><Icon size={18}/>{label}</Link>)}</div></details></nav>:<nav aria-label="Main navigation" className={menu?'open':''}>{[['Home','/home'],['Collections','/collections'],['Designers','/discover'],['Our Story','/our-story'],['Reviews','/reviews']].map(([label,url])=><Link key={url} to={url} className={path===url?'active':''}>{label}</Link>)}</nav>}<div className="header-icons"><Link to="/search" className="icon-button"><Search size={20}/><span className="sr-only">Search</span></Link>{state.user&&<><Link to="/notifications" className="icon-button bag"><Bell size={20}/><span className="sr-only">Notifications</span>{state.notifications.some(n=>!n.read)&&<b>{state.notifications.filter(n=>!n.read).length}</b>}</Link><Link to="/cart" className="icon-button bag"><ShoppingBag size={20}/><span className="sr-only">Shopping bag</span>{cartCount>0&&<b>{cartCount}</b>}</Link><Link to="/wishlist" className="header-action"><Heart size={20}/><span>Wishlist</span></Link><details className="nav-dropdown account-dropdown"><summary className="header-action"><User size={20}/><span>Profile</span></summary><div className="nav-dropdown-panel"><div className="topnav-user"><strong>{state.user.name}</strong><small>Your style, your story</small></div>{sidebar.filter(x=>x[0]==='Your world').map(([,Icon,label,url])=><Link key={url} to={url}><Icon size={18}/>{label}</Link>)}<Link to="/settings"><Settings size={18}/>Settings</Link><Link to="/help"><HelpCircle size={18}/>Help & support</Link><button onClick={signOut}><LogOut size={18}/>Sign out</button></div></details></>}{!state.user&&<Link to="/login" className="header-signin">Sign in</Link>}<button className="icon-button menu-button" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header><div className={workspace?'workspace-layout':''}><main id="main" key={path} tabIndex={-1}>{process.env.NEXT_PUBLIC_VERCEL_DEMO&&<div className="offline-banner">Website demo · Your designs and reviews are saved in this browser. Cloud sign-in and storage are available on the original hosted site.</div>}{!online&&<div className="offline-banner">You’re offline. <Link to="/offline">View saved content</Link></div>}{ready?content:<div className="loading-shell"><div className="skeleton"/><p>{message||'Preparing your world of fashion…'}</p>{message&&<Button onClick={()=>window.location.reload()}>Retry loading</Button>}</div>}</main></div>{!workspace&&<footer><div className="footer-main"><div><Logo/><p>Dream it. Design it. Wear it.</p></div>{[['Discover',['Collections','Designers','Create an outfit','Customer reviews'],['/collections','/discover','/create','/reviews']],['Our world',['Our story','Contact','Welcome','All screens'],['/our-story','/contact','/welcome','/screens']],['Your account',['Sign in','Style quiz','My profile','My orders'],['/login','/onboarding/intro','/profile','/orders']],['Here to help',['Size guide','Help centre','Shipping','Returns & alterations'],['/size-guide','/help','/shipping-policy','/return-policy']]].map(([title,labels,urls])=><div key={String(title)}><h4>{title}</h4>{(labels as string[]).map((label,i)=><Link key={label} to={(urls as string[])[i]}>{label}</Link>)}</div>)}</div><div className="footer-bottom"><span>© 2026 RASAVATT</span><Link to="/screens">Explore all 80 screens</Link><div><Link to="/terms">Terms</Link> · <Link to="/privacy">Privacy</Link></div></div></footer>}{workspace&&<Link to="/screens" className="screen-map-link">Explore all screens</Link>}{message&&<div className="toast" role="status">{message}<button aria-label="Dismiss notification" onClick={()=>setMessage('')}><X size={16}/></button></div>}<Link to="/support" className="support-float">Need a hand?</Link></div></Context.Provider>
}
